#!/bin/bash
echo ""
echo "STARTING: ${BASH_SOURCE}"
echo "VERSION: 2017-01-27"
echo "USER: ${USER}"
export PATH="/usr/X11R6/bin:${PATH}"

########################## SETUP STUDIO WIDE ENVIRONMENT HOOKS

if [ -d ${DABRENDER} ]; then
    echo "CHECK   : DABRENDER SEEMS TO BE THERE ${DABRENDER}"
else
    echo "CRITICAL: Cant see DABRENDER ${DEBRENDER}"
    unset DABRENDER
#     exit 1
fi

######### DABUSR - this is the main location presently for all things in our suite of farm scripts - all kept in git rep
_dabusr="${DABRENDER}/usr"
if [ -d ${_dabusr} ]; then
    #export DABUSR="${_dabusr}"
    echo "INFO    : DABUSR = ${DABUSR}"
else
    echo "CRITICAL: Cant set DABUSR correctly ${_dabusr}"
    unset DABUSR
fi

######## DABSWW - not used yet but a software warehouse hook
_dabsww="${DABRENDER}/sww"
if [ -d ${_dabsww} ]; then
    export DABSWW="${_dabsww}"
    echo "INFO    : DABSWW = ${DABSWW}"
else
    echo "CRITICAL: Cant set DABSWW correctly ${_dabsww}"
    unset DABSWW
fi

######### DABWORK - the main work area hook
_dabwork="${DABRENDER}/work"
if [ -d ${_dabwork} ]; then
    export DABWORK="${_dabwork}"
    echo "INFO    : DABWORK = ${DABWORK}"
else
    echo "CRITICAL: Cant set DABWORK correctly ${_dabwork}"
    unset DABWORK
#     exit 1
fi

######### DABASSETS - an asset library hook
_dabassets="${DABRENDER}/assets"
if [ -d ${_dabassets} ]; then
    export DABASSETS="${_dabassets}"
    echo "INFO    : DABASSETS = ${DABASSETS}"
else
    echo "CRITICAL: Cant set DABASSETS correctly ${_dabassets}"
    unset DABASSETS
fi

######### DABUSERPREFS  this is a place for user preferences to be centrally (in lieu of a home directory)
_dabuserprefs="${DABRENDER}/work/user_prefs"
if [ -d ${_dabuserprefs} ]; then
    export DABUSERPREFS="${_dabuserprefs}"
    echo "INFO    : DABUSERPREFS = ${DABUSERPREFS}"
else
    echo "CRITICAL: Cant set DABUSERPREFS correctly ${_dabuserprefs}"
    unset DABUSERPREFS
fi


##########################
export MAYA_VERSION="2017"
echo "INFO    : MAYA VERSION   : $MAYA_VERSION"
export RMAN_VERSION="21.2"
echo "INFO    : RMAN_VERSION   : $RMAN_VERSION"
export TRACTOR_VERSION="2.2"
echo "INFO    : TRACTOR_VERSION: $TRACTOR_VERSION"
export NUKE_VERSION="10.0v5"
echo "INFO    : NUKE_VERSION   : $NUKE_VERSION"
echo "INFO    : OS             : ${OSTYPE:0:5}"
##########################

case ${OSTYPE:0:5} in

linux)
    export RMANTREE="/opt/pixar/RenderManProServer-${RMAN_VERSION}"
    export RMSTREE="/opt/pixar/RenderManStudio-${RMAN_VERSION}-maya${MAYA_VERSION}"
    export TRACTOR_LOCATION="/opt/pixar/Tractor-${TRACTOR_VERSION}"
    export MAYA_APPLICATION_LOCATION="/usr/autodesk/maya${MAYA_VERSION}"
    export MAYA_LOCATION="${MAYA_APPLICATION_LOCATION}"
    ;;

darwi)
    export RMANTREE="/Applications/Pixar/RenderManProServer-${RMAN_VERSION}"
    export RMSTREE="/Applications/Pixar/RenderManStudio-${RMAN_VERSION}-maya${MAYA_VERSION}"
    export TRACTOR_LOCATION="/Applications/Pixar/Tractor-${TRACTOR_VERSION}"
    export MAYA_APPLICATION_LOCATION="/Applications/Autodesk/maya${MAYA_VERSION}"
    export MAYA_LOCATION="${MAYA_APPLICATION_LOCATION}/Maya.app/Contents"
    export NUKE_INSTALL_PATH="/Applications/Nuke${NUKE_VERSION}"
    export NUKE_LOCATION="${NUKE_INSTALL_PATH}/Nuke$NUKE_VERSION.app"
    export NUKE_TEMP_DIR="/var/tmp/nuke-${USER}"
    export PATH="${NUKE_INSTALL_PATH}/Nuke${NUKE_VERSION}.app/Contents/MacOS:${PATH}"
    export PATH="/usr/aw/COM/bin:/usr/aw/COM/etc:${PATH}"
    export PATH="/Applications/RV64.app/Contents/MacOS:${PATH}"
    ;;

*)
    echo "WARNING:   LIBRARY_PATH and base environment NOT set in profile.d/dabanim.sh"
    ;;

esac

#  $DABUSR and DABRENDER are set in /etc/profile.d/dabanim.sh and is OS aware
#  These are locations for central scripts and python scripts common to osx and linux eg perl, shell, python:wq
#  Not entirely sure what the dirrernce between RDIR and RMS_SCRIPT_PATHS is
export RMS_SCRIPT_PATHS=${DABRENDER}/etc/pixar/configs
export RDIR=${DABRENDER}/etc/pixar/configs
export PIXAR_LICENSE_FILE=${DABRENDER}/etc/pixar/pixar.license
export foundry_LICENSE=${DABRENDER}/etc/foundry/foundry_license.lic
export RV_LICENSE_FILE=${DABRENDER}/etc/tweak/license.gto
export TWEAK_LICENSE_FILE=${DABRENDER}/etc/tweak/license.gto
export MU_MODULE_PATH=${DABRENDER}/usr/etc/tweak/mu
export SGTK_DESKTOP_CONFIG_LOCATION=${DABRENDER}/etc/shotgun

# WORKAROUND for libMC3.so.8 error in Maya2016 (added by Chris Bell 10/9/15
export MAYA_DISABLE_CIP=1

##########################  generic maya settings
# export MAYA_APP_DIR=${DABRENDER}/etc/maya/mayaConfig
# export MAYA_SCRIPT_PATH=${RMSTREE}/scripts:${MAYA_SCRIPT_PATH}
# export MAYA_PLUG_IN_PATH=${RMSTREE}/plug-ins:${MAYA_APPLICATION_LOCATION}/plug-ins:${MAYA_PLUG_IN_PATH}
# export XBMLANGPATH=${RMSTREE}/icons:${XBMLANGPATH}
export MAYA_MAC_SET_UMASK=0

##########################  PATH settings
export PATH=${DABRENDER}/bin:${PATH}
export PATH=${DABUSR}/bin:${PATH}
export PATH=${DABUSR}/software/renderfarm/bin:${PATH}
export PATH=${RMANTREE}/bin:${PATH}
export PATH=${RMSTREE}/bin:${PATH}
export PATH=${TRACTOR_LOCATION}/bin:${PATH}
export PATH=${MAYA_LOCATION}/bin:${PATH}
export PATH=${DABUSR}/etc/tractor:${PATH}

##########################  PYTHONPATH settings
export PYTHONPATH=${RMSTREE}/scripts:${PYTHONPATH}
export PYTHONPATH=${DABUSR}/lib/python:${PYTHONPATH}
export PYTHONPATH=${DABUSR}/software/renderfarm:${PYTHONPATH}
export PYTHONPATH=${DABUSR}/etc/tractor:${PYTHONPATH}
export PYTHONPATH=${DABUSR}:${PYTHONPATH}

########################## copy of tractor package only
##### need to do this as we dont want all the other site-packages from tractor and rmstree like pyside etc
export PYTHONPATH=${DABUSR}/lib/site-packages:${PYTHONPATH}
#export PYTHONPATH=${PYTHONPATH}:${RMSTREE}/lib/python2.7/site-packages
#export PYTHONPATH="${OCIO_EXECROOT}/lib/python2.7/site-packages:${PYTHONPATH}"

##########################  NUKE settings
#export NUKE_PATH="${OCIO_EXECROOT}/lib/nuke:${NUKE_PATH}"
#export NUKE_PATH="${OCIO_ROOT}/share/nuke:${NUKE_PATH}";
#export NUKE_PATH="${DABUSR}/etc/nuke/tractorNuke:${NUKE_PATH}";


###########################  ALIAS's
alias nukex='Nuke${NUKE_VERSION} --nukex'
alias nukestudio='Nuke${NUKE_VERSION} --studio'
alias nukeassist='Nuke${NUKE_VERSION} --nukeassist'
alias nukeple='Nuke${NUKE_VERSION} --PLE'
alias nuke='Nuke${NUKE_VERSION}'
alias maya='maya'
# alias runnuke='source nuke_env'
# alias runmaya='source maya_env'
alias tqd='tq --engine tractor-engine:5600'


# if [ ${CONFIG} ] ; then
# echo  "INFO    : CONFIG is ${CONFIG} "
#     export MAYA_APP_DIR="${CONFIG}/mayaConfig"
# else
# 	echo  "WARNING: CONFIG not found still "
# fi


##########################
echo     "ENDING  : ${BASH_SOURCE}"
echo ""
