@Echo OFF

REM ------------------------------------------------------------------------------
REM
REM Copyright (c) 1986-2016 Pixar. All rights reserved.
REM
REM The information in this file (the "Software") is provided for the exclusive
REM use of the software licensees of Pixar ("Licensees").  Licensees have the
REM right to incorporate the Software into other products for use by other
REM authorized software licensees of Pixar, without fee. Except as expressly
REM permitted herein, the Software may not be disclosed to third parties, copied
REM or duplicated in any form, in whole or in part, without the prior written
REM permission of Pixar.
REM
REM The copyright notices in the Software and this entire statement, including the
REM above license grant, this restriction and the following disclaimer, must be
REM included in all copies of the Software, in whole or in part, and all permitted
REM derivative works of the Software, unless such copies or derivative works are
REM solely in the form of machine-executable object code generated by a source
REM language processor.
REM
REM PIXAR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
REM IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL PIXAR BE
REM LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
REM WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
REM OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
REM CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.  IN NO CASE WILL
REM PIXAR'S TOTAL LIABILITY FOR ALL DAMAGES ARISING OUT OF OR IN CONNECTION WITH
REM THE USE OR PERFORMANCE OF THIS SOFTWARE EXCEED $50.
REM
REM Pixar
REM 1200 Park Ave
REM Emeryville CA 94608
REM
REM ------------------------------------------------------------------------------

REM $Revision: #2 $

@Echo ON

oslc shield.osl
prman trial.rib
cmptiff -q -t .03 trial.tif check.tif

